---
title: "Final Examination"
author: "ManojKumar Chalamala"
date: "12/3/2019"
output: html_document
---

```{r}
library(tidyverse)
install.packages("factoextra")
library(factoextra)
library(ISLR)
set.seed(123)
MyData <- BathSoap
```

The variables that describe purchase behavior (including brand loyalty)

```{r}
MyData1 <- MyData[, c(2:34)]
MyData1 <- scale(MyData1)

fviz_nbclust(MyData1, kmeans, method = "wss")

fviz_nbclust(MyData1, kmeans, method = "silhouette")
```

```{r}
k3 <- kmeans(MyData1, centers = 3, nstart = 25) 
# Visualize the output
k3$centers 
```

```{r}
fviz_cluster(k3, data = MyData1)
```

The variables that describe the basis for purchase

```{r}
MyData2 <- MyData[, c(2:11,19,35:46)]
MyData2 <- scale(MyData2)

fviz_nbclust(MyData2, kmeans, method = "wss")

fviz_nbclust(MyData2, kmeans, method = "silhouette")

Price_k3 <- kmeans(MyData2, centers = 3, nstart = 25) 
# Visualize the output
Price_k3$centers 

fviz_cluster(Price_k3, data = MyData2)
```

```{r}
MyData3 <- MyData[, c(2:46)]
MyData3 <- scale(MyData3)

fviz_nbclust(MyData3, kmeans, method = "wss")

fviz_nbclust(MyData3, kmeans, method = "silhouette")

PB_k3 <- kmeans(MyData3, centers = 3, nstart = 25) 
# Visualize the output
PB_k3$centers 

fviz_cluster(PB_k3, data = MyData3)
```

